# Generated by Django 4.1.1 on 2022-09-15 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animais', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animal',
            old_name='venonoso',
            new_name='venenoso',
        ),
    ]
